# Vienkāršs Ievads Pandas bibliotēkā

Pandas ir jaudīga Python bibliotēka datu analīzei un manipulācijai. Šajā ievadā mēs apskatīsim, kā izmantot Pandas, lai strādātu ar datiem, piemēram, no CSV faila.

Pandas mājas lapa: https://pandas.pydata.org/ - dokumentācija, piemēri, un daudz kas cits!

In [1]:
print("Mūsu pirmā Python piezīmju grāmata!")

Mūsu pirmā Python piezīmju grāmata!

In [ ]:
# pārbaudīsim Pandas versiju
import pandas as pd
print("Pandas versija:", pd.__version__)
# ja šī komanda izvada versiju, tad Pandas ir veiksmīgi instalēts un gatavs lietošanai!
# otrs moments, tagad pd ļaus mums izmantot Pandas funkcijas, piemēram, pd.read_csv() datu ielādei no CSV faila.

Pandas versija: 3.0.1

In [4]:
# jā pandas nav tad uzstādam ar sekojošo komandu:
# pip install pandas
# mums vajag arī lasīt un rakstīt Excel failus, tāpēc uzstādam arī openpyxl bibliotēku:
# pip install openpyxl
# rakstīšanā Excel failā:
# xlslwriter arī
# pip install xlsxwriter
# kopā vienā rindā:
# pip install pandas openpyxl xlsxwriter

# nolasīsism terini.csv failu un izvadīsim to uz ekrāna
# svarīgi lai terini.csv būtu tajā pašā mapē kur atrodas šis Python fails, pretējā gadījumā būs jānorāda pilns ceļš līdz failam
df = pd.read_csv("terini.csv") # nolasām csv failu
# df ir ļoti populārs saīsinājums datu rāmim (dataframe)
print(df) # izvadām datu rāmi uz ekrāna

         Diena  Tēriņi
0    Pirmdiena   30.70
1     Otrdiena   25.50
2    Trešdiena   28.90
3  Ceturtdiena   22.40
4   Piektdiena   35.20
5    Sestdiena   40.00
6    Svētdiena   18.75

In [5]:
# var būt ērtāk izvadīt tikai galvu - head
# otrs print nav obligāts Jupyter Notebook šūnas pēdejā rindā, jo Jupyter automātiski izvada pēdējo objektu, bet tas ir labs ieradums, lai kods būtu saprotamāks un strādātu arī ārpus Jupyter vidē.
df.head() # izvadām datu rāmi uz ekrāna, bet tikai pirmās 5 rindas

         Diena  Tēriņi
0    Pirmdiena    30.7
1     Otrdiena    25.5
2    Trešdiena    28.9
3  Ceturtdiena    22.4
4   Piektdiena    35.2

In [6]:
# aste
# pēdejās 3 rindas
df.tail(3)

        Diena  Tēriņi
4  Piektdiena   35.20
5   Sestdiena   40.00
6   Svētdiena   18.75

In [7]:
# describe mums dod statistiku par skaitliskajiem datiem, piemēram, vidējo vērtību, minimumu, maksimumu, standartnovirzi utt.
df.describe()

          Tēriņi
count   7.000000
mean   28.778571
std     7.335635
min    18.750000
25%    23.950000
50%    28.900000
75%    32.950000
max    40.000000

In [8]:
# šo analīze mēs varam uzreiz arī saglabāt dažādos formātos, piemēram, Excel failā vai CSV failā
# pagaidām tikai CSV
df.describe().to_csv("terini_statistika.csv", index=True) # saglabājam statistiku CSV failā, index=True nozīmē, ka saglabāsim arī indeksu (kolonnas nosaukumus)

In [9]:
# līdzigi var saglabāt arī Excel failā, bet tam ir jānorāda arī engine, jo pēc noklusējuma Pandas izmanto openpyxl, bet mums ir uzstādīts arī xlsxwriter, tāpēc jānorāda kurš engines izmantot:
df.describe().to_excel("terini_statistika.xlsx", index=True, engine="xlsxwriter") # saglabājam statistiku Excel failā, index=True nozīmē, ka saglabāsim arī indeksu (kolonnas nosaukumus), engine="xlsxwriter" nozīmē, ka izmantosim xlsxwriter bibliotēku Excel faila rakstīšanai

In [10]:
# kādas kolonas mums ir?
print(df.columns) # izvadām kolonnu nosaukumus

Index(['Diena', 'Tēriņi'], dtype='str')

In [11]:
# apskatīsim visus tēriņus virs 30
virs_30  = df[df["Tēriņi"] > 30] #   filtrējam datu rāmi, lai iegūtu tikai tās rindas, kur tēriņi ir lielāki par 30
virs_30

        Diena  Tēriņi
0   Pirmdiena    30.7
4  Piektdiena    35.2
5   Sestdiena    40.0